spring:
  security:
    oauth2:
      authorizationserver:
        issuer: "http://auth.local:9000"

proptech:
  webclient:
    clients:
      user-service:
        base-url: "http://user-service:8080"