services:
  user-db:
    image: postgres:18-alpine
    container_name: user-postgres-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${USER_POSTGRES_DB}
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_POSTGRES_USER} -d ${USER_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  customer-db:
    image: postgres:18-alpine
    container_name: customer-postgres-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${CUSTOMER_POSTGRES_DB}
      POSTGRES_USER: ${CUSTOMER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CUSTOMER_POSTGRES_PASSWORD}
    volumes:
      - customer-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CUSTOMER_POSTGRES_USER} -d ${CUSTOMER_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  property-db:
    image: postgres:18-alpine
    container_name: property-postgres-db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ${PROPERTY_POSTGRES_DB}
      POSTGRES_USER: ${PROPERTY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROPERTY_POSTGRES_PASSWORD}
    volumes:
      - property-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PROPERTY_POSTGRES_USER} -d ${PROPERTY_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:4.1.4-management-alpine
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running", "-q" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-session:
    image: redis:8.2.2-alpine
    container_name: redis-session
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-session-data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user-postgres-data:
  customer-postgres-data:
  property-postgres-data:
  rabbitmq-data:
  redis-session-data:

networks:
  app-network:
    driver: bridge
    name: app-network