services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: nndrez/auth-service
    container_name: auth-service
    restart: on-failure
    ports:
      - "9000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network
    depends_on:
      user-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: nndrez/api-gateway
    container_name: api-gateway
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_HOST: redis-session
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - app-network
    extra_hosts:
      - "auth.local:host-gateway"
    depends_on:
      auth-service:
        condition: service_healthy
      customer-service:
        condition: service_healthy

  redis-session:
    image: redis:8.2.2-alpine
    container_name: redis-session
    restart: always
    networks:
      - app-network
    ports:
      - "6379:6379"
    volumes:
      - redis-session-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-db:
    image: postgres:18-alpine
    container_name: user-postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${USER_POSTGRES_DB}
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_POSTGRES_USER} -d ${USER_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: nndrez/user-service
    container_name: user-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/${USER_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${USER_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_POSTGRES_PASSWORD}
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  customer-db:
    image: postgres:18-alpine
    container_name: customer-postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${CUSTOMER_POSTGRES_DB}
      POSTGRES_USER: ${CUSTOMER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CUSTOMER_POSTGRES_PASSWORD}
    volumes:
      - customer-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CUSTOMER_POSTGRES_USER} -d ${CUSTOMER_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    image: nndrez/customer-service
    container_name: customer-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://customer-db:5432/${CUSTOMER_POSTGRES_DB:?Customer postgres DB not defined}
      SPRING_DATASOURCE_USERNAME: ${CUSTOMER_POSTGRES_USER:?Customer postgres user not defined}
      SPRING_DATASOURCE_PASSWORD: ${CUSTOMER_POSTGRES_PASSWORD:?Customer Postgres password not defined}
    depends_on:
      customer-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4.1.4-management-alpine
    container_name: rabbitmq
    restart: on-failure
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running", "-q" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    image: nndrez/email-service
    container_name: email-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST:?Host email not defined}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT:?Host email port not defined}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME?:Email username not defined}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD?:Email password not defined}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:-true}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:-true  }
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  user-postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  rabbitmq-data:
    driver: local
  grafana-data:
    driver: local
  elasticsearch-data:
    driver: local
  customer-postgres-data:
    driver: local
  redis-session-data:
    driver: local

networks:
  app-network:
    driver: bridge