services:
  user-db:
    image: postgres:18-alpine
    container_name: user-postgres-db-local
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - user-postgres-data-local:/var/lib/postgresql/data
    networks:
      - local-network

  customer-db:
    image: postgres:18-alpine
    container_name: customer-postgres-db-local
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_DB: customer-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - customer-postgres-data-local:/var/lib/postgresql/data
    networks:
      - local-network

  rabbitmq:
    image: rabbitmq:4.1.4-management-alpine
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data-local:/var/lib/rabbitmq
    networks:
      - local-network

  redis-session-local:
    image: redis:8.2.2-alpine
    container_name: redis-session-local
    ports:
      - "6379:6379"
    volumes:
      - redis-session-data-local:/data
    networks:
      - local-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-local
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data-local:/var/lib/pgadmin
    depends_on:
      - user-db
    networks:
      - local-network

volumes:
  user-postgres-data-local:
  customer-postgres-data-local:
  rabbitmq-data-local:
  pgadmin-data-local:
  redis-session-data-local:

networks:
  local-network:
    driver: bridge