spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://auth.local:9000
            authorization-uri: http://auth.local:9000/oauth2/authorize
            token-uri: http://auth-service:8080/oauth2/token
            jwk-set-uri: http://auth-service:8080/oauth2/jwks
            user-info-uri: http://auth-service:8080/userinfo
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: api-gateway-proxy
              uri: http://api-gateway:8080
              predicates:
                - Path=/api/v1/**
              filters:
                - TokenRelay=
                - RemoveRequestHeader=Cookie